---
title: "Explore AquaX redlist"
format: 
  html:
    toc: true
    number-sections: true
    embed-resources: true
execute:
    message: false
    warning: false
---

```{r}
library(tidyverse)
library(here)
library(janitor)
```

```{r}
# read in meta data on the aquax sample of redlist species
load("/home/shares/usgs-cap-rangeshifts/data_aquax/iucn/meta.Rdata")
```

```{r}
# count spp in each group
meta_group <- meta %>% 
  group_by(GROUP) %>% 
  summarize(n = n()) %>% 
  ungroup()

meta_group
```
```{r}
# IUCN threat info
iucn <- read.csv("/home/shares/usgs-cap-rangeshifts/data_iucn/iucn_to_worms_match_redlist_category.csv")
```

```{r}
meta_clean <- meta %>% 
  mutate(worms_name = tolower(ScientificName)) %>% 
  select(!ScientificName) %>% 
  # simplify for now for easier viewing
  select(AphiaID, SPID, worms_name, GROUP, NR_CR, range_pixels, SDM)
```

```{r}
# Merge in IUCN info based on the worms_name
meta_iucn <- left_join(meta_clean, 
                       # merge in IUCN data and filter for species (no subpops)
                       iucn %>%  filter(species == TRUE),
                       by = "worms_name")
```

```{r}
# Drop those without IUCN sid (get 13,132 species remaining)
meta_iucn_no_na <- meta_iucn %>% 
  filter(!is.na(iucn_sid))
```

```{r}
# May be duplicates (90 cases where AquaX/worms is two or more species in IUCN)
# Might just remove these for now
df_worms_iucn_dupes <- meta_iucn_no_na %>% 
  get_dupes(worms_name)

dupes <- unique(df_worms_iucn_dupes$worms_name)
```

```{r}
# Drop those 90 worms species that are representing 2+ IUCN species 
# 12,940 species remaining
meta_iucn_no_na_no_dupes <- meta_iucn_no_na %>% 
  filter(!worms_name %in% dupes)
```

```{r}
# After filtering, what is the distribution of IUCN threat categories?
meta_iucn_cat <- meta_iucn_no_na_no_dupes %>% 
  group_by(iucn_category) %>% 
  summarize(n = n()) %>% 
  ungroup()

meta_iucn_cat
```

```{r}
# After filtering, what is the distribution of IUCN threat categories by group?
meta_iucn_cat_group <- meta_iucn_no_na_no_dupes %>% 
  group_by(iucn_category, GROUP) %>% 
  summarize(n = n()) %>% 
  ungroup()
```

```{r}
meta_iucn_cat_group_threat <- meta_iucn_cat_group %>% 
  filter(iucn_category %in% c("Critically Endangered",
                              "Endangered", "Vulnerable"))
```

```{r}
ggplot(data = meta_iucn_cat_group_threat,
       aes(x = GROUP, y = n, fill = iucn_category)) + 
  geom_bar(stat = "identity", position = position_dodge())
```

