---
title: "AquaX and IUCN status"
format: 
  html:
    toc: true
    number-sections: true
    embed-resources: true
execute:
    message: false
    warning: false
---

```{r}
library(tidyverse)
library(here)
library(iucnredlist) ### remotes::install_github("IUCN-UK/iucnredlist")
library(janitor)
```

This document finds the IUCN threat information for the AquaX species

```{r}
aquax_iucn <- read_csv("data/2024_ohara_iucn_to_worms_match.csv")
```

```{r}
api_key <- Sys.getenv("IUCN_API_KEY") ### usethis::edit_r_environ() to add key to R environment file
api <- init_api(api_key)
```

```{r}
# Get sample
aquax_iucn_30 <- aquax_iucn[1:30,]
```

```{r}
iucn_id <- function(api, sis_id){
  # get species info
  species_info <- #if (FALSE) # don't run
    {assessments_by_sis_id(api,sis_id)}
  list_status <- species_info %>%
    filter(latest == TRUE & scopes_code == 1) #%>%
  #filter(year_published == max(year_published))
  return(list_status$assessment_id)
}
```

```{r}
# Pull iucn_sid
iucn_sid_30 <- aquax_iucn_30$iucn_sid
iucn_sid <- aquax_iucn$iucn_sid
```

```{r}
sample <- assessments_by_sis_id(api, 235)
sample_short <- assessments_by_sis_id(api, 229)
```

```{r}
# Replace incorrect ids (most of these are referencing a subspecies - updated to full species id)
# Replace 21861 id with 21856 (repeated so do twice)
iucn_sid[410] <- 21856
iucn_sid[411] <- 21856
iucn_sid[486] <- 3853
iucn_sid[683] <- 41745
iucn_sid[4015] <- 42838
```

```{r}
# Loop through function, save as list
iucn_id_list <- list()
for(i in 1:nrow(aquax_iucn)){
  test <- iucn_id(api, iucn_sid[i])
  iucn_id_list[[i]] <- test
}
```

```{r}
iucn_id_vector <- unlist(iucn_id_list)
```

```{r}
saveRDS(iucn_id_vector, "iucn_id_vector_041726.rds")
```

```{r}
# Run the assessment numbers collected from the iucn_id function
# Note that 16,429 values went into the function, but api found 16,413 unique assessment IDs
iucn_id_data <- assessment_data_many(api, iucn_id_vector, wait_time = 0.5)
```

```{r}
saveRDS(iucn_id_data, "iucn_id_data_041726.rds")
```

```{r}
# run element names to extract
iucn_status <- extract_element(iucn_id_data, "red_list_category")
```

```{r}
# run element names to extract
sis_taxon_id <- extract_element(iucn_id_data, "sis_taxon_id")
```

```{r}
# run element names to extract
iucn_names <- extract_element(iucn_id_data, "taxon")
```

```{r}
iucn_sis_status <- left_join(sis_taxon_id, iucn_status, by = "assessment_id")
iucn_sis_status_names <- left_join(iucn_sis_status, iucn_names,
                                           by = "assessment_id") %>% 
  select(sis_id, assessment_id, scientific_name, description, code) %>% 
    rename(iucn_category = description,
           iucn_category_code = code,
           iucn_sid = sis_id)
```

```{r}
# Replace the same sis_ids 
aquax_iucn_clean <- aquax_iucn

aquax_iucn_clean[410,1] <- 21856
aquax_iucn_clean[411,1] <- 21856
aquax_iucn_clean[486,1] <- 3853
aquax_iucn_clean[683,1] <- 41745
aquax_iucn_clean[4015,1] <- 42838
```

```{r}
# merge the iucn data with the crosswalk
aquax_iucn_clean_threat <- inner_join(aquax_iucn_clean, iucn_sis_status_names)

```
```{r}
# Warning that some rows had many-to-many match, but will save for now (sid 17030 and 21856)
write_csv(aquax_iucn_clean_threat, "/home/abowd/R/repos/aquax_sample/data/iucn_to_worms_match_redlist_category.csv")
```

