---
title: "EEZs and AquaX Redlist"
format: 
  html:
    toc: true
    number-sections: true
    embed-resources: true
execute:
    message: false
    warning: false
---

```{r}
library(tidyverse)
library(terra)
library(sf)
library(here)
library(janitor)
library(arrow)
```

## EEZ 

```{r}
eez <- st_read('/home/shares/usgs-cap-rangeshifts/spatial/World_EEZ_v12_20231025_gpkg/eez_v12.gpkg')
```

```{r}
# Create a blank raster matching AquaX resolution (EEZs should be large enough to just do 0.05 degree raster)
eez_raster_blank <- rast(xmin = -180,
                  xmax = 180,
                  ymin = -90, 
                  ymax = 90,
                  resolution = 0.05)
```

```{r}
eez_raster_output <- rasterize(eez, eez_raster_blank, field = "GEONAME")
```

## Prep AquaX redlist data

```{r}
# read in meta data on the aquax sample of redlist species
load("/home/shares/usgs-cap-rangeshifts/data_aquax/iucn/meta.Rdata")
```

```{r}
# IUCN threat info
iucn <- read.csv("/home/shares/usgs-cap-rangeshifts/data_iucn/iucn_to_worms_match_redlist_category.csv")
```

```{r}
meta_clean <- meta %>% 
  mutate(worms_name = tolower(ScientificName)) %>% 
  select(!ScientificName) %>% 
  # simplify for now for easier viewing
  select(AphiaID, SPID, worms_name, GROUP, NR_CR, range_pixels, SDM)
```

```{r}
# Merge in IUCN info based on the worms_name
meta_iucn <- left_join(meta_clean, 
                       # merge in IUCN data and filter for species (no subpops)
                       iucn %>%  filter(species == TRUE),
                       by = "worms_name")
```

```{r}
# Drop those without IUCN sid (get 13,132 species remaining)
meta_iucn_no_na <- meta_iucn %>% 
  filter(!is.na(iucn_sid))
```

```{r}
# May be duplicates (90 cases where AquaX/worms is two or more species in IUCN)
# Might just remove these for now
df_worms_iucn_dupes <- meta_iucn_no_na %>% 
  get_dupes(worms_name)

dupes <- unique(df_worms_iucn_dupes$worms_name)
```

```{r}
# Drop those 90 worms species that are representing 2+ IUCN species 
# 12,940 species remaining
meta_iucn_no_na_no_dupes <- meta_iucn_no_na %>% 
  filter(!worms_name %in% dupes)
```

```{r}
# For now, focusing on only threatened species (1,013 species)
meta_iucn_threatened <- meta_iucn_no_na_no_dupes %>% 
  filter(iucn_category %in% c("Critically Endangered",
                              "Endangered", "Vulnerable"))
```

```{r}
# Get AphiaID of threatened species
aphiaid_threatened <- meta_iucn_threatened$AphiaID
```

## Prep AquaX data
Here, there are just the 12,238 files -not totally sure why the files and meta data don't exactly line up. But when I filter for the 1,013 threatened AphiaIDs, I get 906 species.

```{r}
spp_fs <- list.files('/home/shares/usgs-cap-rangeshifts/data_aquax/iucn/SDM',
                     full.names = TRUE)

df <- data.frame(f = spp_fs) %>%
    mutate(fsize = file.size(f),
           aphiaid = str_extract(basename(f), '[0-9]+') %>% as.integer()) %>%
    left_join(meta, by = c('aphiaid' = 'AphiaID'))
```

```{r}
# Filter for the AphiaID of the threatend species (906)
df_threatened <- df %>% 
  filter(aphiaid %in% aphiaid_threatened)
```

```{r}
test_f <- read_parquet("/home/shares/usgs-cap-rangeshifts/data_aquax/iucn/SDM/FINAL_EMSDM_EMMEAN_SP_1006832.parquet")
```

```{r}
set.seed(123)
test_spp_30 <- slice_sample(df_threatened, n = 30)
files_30 <- test_spp_30$f
aphiaid_30 <- test_spp_30$aphiaid
```

```{r}
extract_eez <- function(id, df) {
  spp_filter <- df %>% 
    filter(aphiaid == id) 
  
  spp_f <- read_parquet(spp_filter$f)
  
  spp <- spp_f %>% 
    mutate(aphiaid = id) 
  
  r_spp <- rast(spp, crs = "EPSG:4326")
  
  # extend spp to the same extent as eez
  r_spp_ex <- extend(r_spp, ext(eez_raster_output))
  
  r_spp_eez <- c(r_spp_ex, eez_raster_output)
  
  spp_df <- as.data.frame(r_spp_eez, xy = TRUE) %>% 
    filter(!is.na(GEONAME)) %>%
    filter(!is.na(Current) | !is.na(RCP85_2100)) %>%
    group_by(GEONAME, aphiaid) %>%
    summarize(n_current = sum(Current >= cutoff),
              n_RCP85_2100 = sum(RCP85_2100 >= cutoff))
  
  return(spp_df)
}
```

```{r}
# Try // - took 2 min
system.time({
  eez_list <- parallel::mclapply(aphiaid_30, FUN = extract_eez, df = test_spp_30, mc.cores = 10)
})
```

```{r}
eez_list_all <- bind_rows(eez_list) %>% 
  mutate(status = case_when(n_current == 0 &  n_RCP85_2100 > 0 ~ 'entry into new',
                            n_current > 0  & n_RCP85_2100 == 0 ~ 'exit from historical',
                            n_current == 0 & n_RCP85_2100 == 0 ~ 'no presence',
                            TRUE ~ 'continued presence'))
```

## Test out full threatened sample

```{r}
files <- df_threatened$f
aphiaid <- df_threatened$aphiaid
```

```{r}
# Try // - took 21 min
system.time({
  eez_list_threatened <- parallel::mclapply(aphiaid, FUN = extract_eez, df = df, mc.cores = 20)
})
```

```{r}
eez_list_threatened <- bind_rows(eez_list_threatened) %>% 
  mutate(status = case_when(n_current == 0 &  n_RCP85_2100 > 0 ~ 'entry into new',
                            n_current > 0  & n_RCP85_2100 == 0 ~ 'exit from historical',
                            n_current == 0 & n_RCP85_2100 == 0 ~ 'no presence',
                            TRUE ~ 'continued presence'))
```