---
title: "Convert .Rdata to .parquet"
author: "Casey"
format: html
---

```{r}
library(tidyverse)
library(arrow)
```

```{r}
sdm_rdata_loc <- '/home/shares/data-aquax/sdm_rdata'
sdm_parquet_loc <- '/home/shares/data-aquax/SDM'

sdm_df <- data.frame(rdata_f = list.files(sdm_rdata_loc, full.names = TRUE)) %>%
  mutate(parquet_f = str_replace(rdata_f, sdm_rdata_loc, sdm_parquet_loc) |> str_replace('.Rdata', '.parquet'),
         xfer_done = file.exists(parquet_f))
         
sdm_todo <- sdm_df %>% filter(!xfer_done)


rdata_to_parquet <- function(i, check = TRUE) {
  ### i <- 1
  sdm_source <- sdm_todo[i, ]$rdata_f
  sdm_out    <- sdm_todo[i, ]$parquet_f
  
  if(file.exists(sdm_out)) {
    message('   file ', basename(sdm_out), ' exists... skipping!')
    return()
  }
  
  load(sdm_source) ### loads in as FINALEMMEAN
  write_parquet(FINALEMMEAN, sink = sdm_out)
  
  if(!check) next()
  ### Check: read in parquet, anti-join to original across all vars:
  ### * if nrow of anti_join is not zero, error!
  ### * if nrow of anti_join is zero, unlink original?
  df <- read_parquet(sdm_out) %>% as.data.frame()
  check <- anti_join(FINALEMMEAN, df)
  if(nrow(check) != 0) stop('FINALEMMEAN from .Rdata is not exactly equal to parquet!')
  
  return(TRUE)
}

tmp_out <- parallel::mclapply(seq_along(sdm_todo$rdata_f), FUN = rdata_to_parquet, mc.cores = 20)

```

verify all .Rdata transferred to .parquet, and then delete

```{r}
#| eval: false
#| 
sdm_parquet_fs <- sdm_df$parquet_f
if(all(file.exists(sdm_parquet_fs))) {
  ### transfer complete!
  unlink(sdm_rdata_fs)
}
```
