---
title: "Exploring Parquet as storage option for AquaX"
format: 
  html:
    toc: true
    number-sections: true
    embed-resources: true
execute:
    message: false
    warning: false
---

```{r}
library(tidyverse)
library(terra)
library(arrow)
```

```{r}
load('data/META_02122025.Rdata')
```

## Build species information

Associate SDM files with the metadata for the 564 sampled species
```{r}
spp_fs <- list.files('/home/shares/usgs-cap-rangeshifts/data_aquax/2026_OHARA_TST_MORPHO/SDM', full.names = TRUE)

df <- data.frame(f = spp_fs) %>%
    mutate(fsize = file.size(f),
           aphiaid = str_extract(basename(f), '[0-9]+') %>% as.integer()) %>%
    left_join(META, by = c('aphiaid' = 'AphiaID'))
```

## Inspect a test species

Identify the structure of the SDM .Rdata for a single species


```{r}
set.seed(123)
test_spp <- slice_sample(df, n = 20) %>%
  select(f, fsize, aphiaid)

for(i in 1:nrow(test_spp)) {
  s <- test_spp[i, ]
  spp_id <- s$aphiaid
  message(i, ' spp ', spp_id)

  load(s$f)
  
  parquet_f <- paste0('test_', spp_id, '.parquet')
  write_parquet(FINALEMMEAN, sink = parquet_f)

  parquet_f2 <- paste0('test2_', spp_id, '.parquet')

  ### write as temp parquet
  write_parquet(FINALEMMEAN %>%
                  select(-cutoff, -AUC, -TSS) %>%
                  mutate(across(-c(x, y), ~as.integer(.x))),
                sink = parquet_f2)
}
```

```{r}
parquet_df <- data.frame(parq_f = list.files('.', pattern = 'test_.+.parquet$'),
                         parq2_f = list.files('.', pattern = 'test2_.+.parquet$')) %>%
  mutate(aphiaid = str_extract(parq_f, '[0-9]+') %>% as.integer(),
         fsize_parquet = file.size(parq_f),
         fsize_parquet2 = file.size(parq2_f)) %>%
  left_join(test_spp, by = 'aphiaid') %>%
  mutate(fsize_reduc = (fsize - fsize_parquet) / fsize,
         fsize_reduc2 = (fsize - fsize_parquet2) / fsize)

mean_reduc <- sum(parquet_df$fsize - parquet_df$fsize_parquet) / sum(parquet_df$fsize)
mean_reduc2 <- sum(parquet_df$fsize - parquet_df$fsize_parquet2) / sum(parquet_df$fsize)

ggplot(parquet_df, aes(x = fsize, y = fsize_parquet, color = fsize_reduc)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, color = 'red')
```


```{r}
spp_big <- parquet_df %>% filter(aphiaid == 137119)
load(spp_big$f); check_df1 <- FINALEMMEAN
check_df2 <- read_parquet(spp_big$parq_f)
check_df3 <- read_parquet(spp_big$parq2_f)

head(check_df3)

check12 <- lapply(1:13, FUN = function(i) {
  sum(check_df1[ , i] - check_df2[ , i], na.rm = TRUE)
}) %>% unlist() %>% sum()
check23 <- lapply(1:1, FUN = function(i) {
  sum(check_df3[ , i] - check_df2[ , i], na.rm = TRUE)
}) %>% unlist() %>% sum()
```

```{r}
x <- list.files('.', pattern = '^test_*.*|^test2_*.*', full.names = TRUE)

unlink(x)
```

