---
title: "Plots of Threatened Species Ranges & EEZs"
format: 
  html:
    toc: true
    number-sections: true
    embed-resources: true
execute:
    message: false
    warning: false
---

```{r}
library(tidyverse)
library(here)
library(janitor)
library(sf)
library(terra)
library(arrow)
```

This document creates plots for the data calculated in 01_iucn_aquax_eez_overlap.qmd and 02_iucn_aquax_rangearea.qmd.

## Read in threatened species data

```{r}
# Spp in EEZs
spp_eez_pxl_count <- read_csv(here("data/iucn_threatened_spp_eez_pxls_052126.csv"))
```

```{r}
# Spp EEZ entry/exit pixels
spp_entry_pxls <- read_rds(here("data/iucn_threatened_entry_pxls_052126.rds"))
spp_exit_pxls <- read_rds(here("data/iucn_threatened_exit_pxls_052126.rds"))
```
```{r}
# Species range area
area_df <- read_csv(here("data/iucn_threatened_spp_range_area_052826.csv"))
```

## Read in EEZ shapefile
```{r}
eez <- st_read('/home/shares/usgs-cap-rangeshifts/spatial/World_EEZ_v12_20231025_gpkg/eez_v12.gpkg')

eez_simple <- eez %>% 
  dplyr::select(MRGID, GEONAME)
```

```{r}
# Create a blank raster matching AquaX resolution (EEZs should be large enough to just do 0.05 degree raster)
eez_raster_blank <- rast(xmin = -180,
                  xmax = 180,
                  ymin = -90, 
                  ymax = 90,
                  resolution = 0.05)
```

```{r}
eez_raster_geoname <- rasterize(eez, eez_raster_blank, field = "GEONAME")
```

## Plot species pixels

```{r}
# Convert to equal area projection for plotting
eez_eq <- st_transform(eez, crs = "EPSG:8857")
```

```{r}
spp_entry_85_2050 <- spp_entry_pxls %>% 
    filter(scenario == "RCP85_2050")

spp_exit_85_2050 <- spp_exit_pxls %>% 
    filter(scenario == "RCP85_2050")
```

```{r}
# Convert to equal area projection for plotting
spp_entry_85_2050_r <- rast(spp_entry_85_2050, crs = "EPSG:4326") %>% 
  project("EPSG:8857", method = "near")

spp_exit_85_2050_r <- rast(spp_exit_85_2050, crs = "EPSG:4326") %>% 
  project("EPSG:8857", method = "near")
```

```{r}
# Back to df for ggplot
spp_entry_85_2050df_eq <- as.data.frame(spp_entry_85_2050_r , xy = TRUE) 
spp_exit_85_2050df_eq <- as.data.frame(spp_exit_85_2050_r , xy = TRUE) 
```

```{r}
# Plot EEZ entry pixels
ggplot() +
  geom_sf(data = eez_eq) +
  geom_tile(data = spp_entry_85_2050df_eq, aes(x = x, y = y,
                                               fill = n_entry_spp,
                                               color = n_entry_spp)) +
  scale_fill_viridis_c(limits = c(1,21), direction = -1) +
  scale_color_viridis_c(limits = c(1,21), direction = -1) +
  theme_minimal()
```


```{r}
# Plot EEZ exit pixels
ggplot() +
  geom_sf(data = eez_eq) +
  geom_tile(data = spp_exit_85_2050df_eq, aes(x = x, y = y,
                                               fill = n_exit_spp,
                                               color = n_exit_spp)) +
  scale_fill_viridis_c(limits = c(1,21), direction = -1) +
  scale_color_viridis_c(limits = c(1,21), direction = -1) +
  theme_minimal()
```

## Plot some areas with high numbers of entries/exits
```{r}
ggplot() +
  geom_sf(data = eez_eq %>% filter(MRGID %in% c("8328", "48955", "48950"))) +
  geom_tile(data = spp_entry_85_2050df_eq %>% 
            filter(MRGID %in% c("8328", "48955", "48950")), 
            aes(x = x, y = y,
            fill = n_entry_spp,
            color = n_entry_spp)) +
  scale_fill_viridis_c(limits = c(1,21), direction = -1) +
  scale_color_viridis_c(limits = c(1,21), direction = -1) +
  theme_minimal() +
  labs(title = "EEZs with most threatened species entries under RCP8.5 2050",
       subtitle = "Top 3 EEZs: North Korea, Lincourt Rocks, and Kuril Islands")
```


```{r}
ggplot() +
  geom_sf(data = eez_eq %>% filter(MRGID %in% c("64440", "8485"))) +
  geom_tile(data = spp_exit_85_2050df_eq %>% 
            filter(MRGID %in% c("64440", "8485")), 
            aes(x = x, y = y,
            fill = n_exit_spp,
            color = n_exit_spp)) +
  scale_fill_viridis_c(limits = c(1,21), direction = -1) +
  scale_color_viridis_c(limits = c(1,21), direction = -1) +
  theme_minimal() +
  labs(title = "EEZs with most threatened species exits under RCP8.5 2050",
       subtitle = "Top 2 EEZs: Singapore / Malaysia, Singapore")
```

## Other plots 

```{r}
# How many EEZs are each spp present in for current and future?
eez_spp_counts <- spp_eez_pxl_count %>%  
  group_by(aphiaid) %>% 
  summarize(current_eez_count = sum(n_current > 0, na.rm = TRUE),
            RCP45_2050_eez_count = sum(n_RCP45_2050 >0, na.rm = TRUE),
            RCP45_2100_eez_count = sum(n_RCP45_2100 > 0, na.rm = TRUE),
            RCP85_2050_eez_count = sum(n_RCP85_2050 > 0, na.rm = TRUE),
            RCP85_2100_eez_count = sum(n_RCP85_2100 > 0, na.rm = TRUE)) %>% 
  ungroup() 
```

```{r}
ggplot() +
  geom_point(data = eez_spp_counts, aes(x = current_eez_count, y = RCP85_2050_eez_count),
             alpha = 0.5, color = "maroon") +
  geom_point(data = eez_spp_counts, aes(x = current_eez_count, y = RCP85_2100_eez_count),
             alpha = 0.5, color = "forestgreen") +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black") +
  labs(title = "IUCN Threatened Species EEZ count (2050 in maroon, 2100 in green)",
       y = "RCP 85 future EEZ count")
```


```{r}
# Organize dataframe so that's it's easier to select a scenario and compare to current
eez_spp_pxls_long <- spp_eez_pxl_count %>% 
  pivot_longer(cols = starts_with("n_RCP"),
               names_to = "scenario",
               values_to = "pxl_count") %>% 
  mutate(scenario = str_remove(scenario, "n_")) %>% 
  mutate(spp_change = case_when(is.na(n_current) &  pxl_count > 0 ~ 'entry into new',
                            n_current > 0  & is.na(pxl_count) ~ 'exit from historical',
                            is.na(n_current)  & is.na(pxl_count) == 0 ~ 'no presence',
                            TRUE ~ 'continued presence'))
```

```{r}
# Get counts of entry into new, exit from historical etc. by EEZ
eez_spp_change <- eez_spp_pxls_long %>% 
  group_by(GEONAME, scenario, spp_change) %>% 
  summarize(spp_change_count = n()) %>% 
  ungroup()
```

```{r}
eez_c_f <- eez_spp_change %>% 
  mutate(spp_change = str_replace_all(spp_change, " ", "_")) %>% 
  pivot_wider(names_from = spp_change, values_from = spp_change_count) %>% 
  replace_na(list(continued_presence = 0, exit_from_historical = 0,
                  entry_into_new = 0, no_presence = 0)) %>% 
  mutate(current_spp = continued_presence + exit_from_historical,
         future_spp = continued_presence + entry_into_new,
         spp_change = future_spp - current_spp,
         ssi = (2 * continued_presence)/(current_spp + future_spp)) 
```

```{r}
# Had a way to color by latitude (Y1) - need to add that in
ggplot() +
  geom_point(data = eez_c_f,
   aes(color = "GEONAME", x = current_spp, y = future_spp), alpha = 0.75, 
             position = position_jitterdodge()) +
  #scale_color_viridis_c() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray30") +
  labs(color = "latitude",
       title = "Current and future spp by EEZ",
       y = "future species count",
       x = "current species count") +
  theme_bw() +
  facet_wrap(~scenario)
```

```{r}
# Had a way to color by latitude (Y1) - need to add that in
ggplot() +
  geom_point(data = eez_c_f, aes(color = "GEONAME", x = exit_from_historical, y = entry_into_new), alpha = 0.75, 
             position = position_jitterdodge()) +
  #scale_color_viridis_c() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray30") +
  labs(#color = "latitude",
       title = "Threatened species loss and gain by EEZ",
       y = "species gain count",
       x = "species loss count") +
  theme_bw() +
  facet_wrap(~scenario)
```

```{r}
# Add sf 
eez_c_f_sf <- left_join(eez_c_f, eez_simple)
```

```{r}
# Threatened species change
ggplot() +
  geom_sf(data = eez_c_f_sf, aes(geometry = geom, fill = spp_change)) +
  scale_color_distiller(palette = "BrBG", direction = 1, limits = c(-75, 75)) + 
  scale_fill_distiller(palette = "BrBG", direction = 1, limits = c(-75, 75)) +
  theme_bw() +
  labs(title = "Threatened species change by EEZ") +
  facet_wrap(~scenario)
```

## Test biplot

```{r}
# Merge the entry and exit dataframes
entry_exit_spp_count_pxl <- full_join(spp_entry_pxls, spp_exit_pxls) 
```

```{r}
entry_exit_spp_sqrt <- entry_exit_spp_count_pxl %>% 
    filter(scenario == "RCP85_2100") %>%
  replace_na(list(n_entry_spp = 0)) %>% 
  replace_na(list(n_exit_spp = 0)) %>% 
  mutate(n_entry_spp_sqrt = sqrt(n_entry_spp),
         n_exit_spp_sqrt = sqrt(n_exit_spp))
```


```{r}
library(biscale)
library(cowplot)
```

```{r}
biplot_data <- bi_class(entry_exit_spp_sqrt, x = n_entry_spp_sqrt, y = n_exit_spp_sqrt,
                        style = "equal", dim = 3)
```

```{r}
biplot_85_2100 <- ggplot() + 
  geom_tile(data = biplot_data, mapping = aes(fill = bi_class,
                                              color = bi_class,
                                              x = x, y = y), show.legend = FALSE) +
  bi_scale_fill(pal = "DkBlue2", dim = 3, rotate_pal = FALSE) +
  bi_scale_color(pal = "DkBlue2", dim = 3, rotate_pal = FALSE) +
  geom_sf(data = eez, fill = NA) +
  labs(x = "",
       y = "",
       subtitle = "RCP 8.5 2100 spp change") +
  bi_theme()
```

```{r}
legend <- bi_legend(pal = "DkBlue2",
                    dim = 3,
                    xlab = "More new spp ",
                    ylab = "More loss spp",
                    size = 8)
```

```{r}
final_plot_85_2100 <- ggdraw() +
  draw_plot(biplot_85_2100, 0, 0, 1, 1) +
  draw_plot(legend, .8, .8, 0.2, 0.2)
```

```{r}
final_plot_85_2100
```




