---
title: "Additional plots"
format: 
  html:
    toc: true
    number-sections: true
    embed-resources: true
execute:
    message: false
    warning: false
---

```{r}
library(tidyverse)
library(here)
library(janitor)
library(sf)
library(terra)
library(arrow)
library(patchwork)
library(cowplot)
library(collapse)
```

This document creates some more focused plots for the data calculated in 01_iucn_aquax_eez_overlap_db.qmd and 02_iucn_aquax_rangearea.qmd. It saves figures for RCP 4.5 2050 and the 1 pxl threshold.

## Read in threatened species data

```{r}
# Spp in EEZs
spp_eez_pxl_count <- read_csv(here("data/iucn_threatened_spp_eez_pxls_061626.csv"))
```

```{r}
# Spp EEZ entry/exit pixels
spp_entry_pxls <- read_rds(here("data/iucn_atrisk_1pxlthres_entry_pxls_091626.rds"))
spp_exit_pxls <- read_rds(here("data/iucn_atrisk_1pxlthres_exit_pxls_091626.rds"))
```

```{r}
# Species range area
area_df <- read_csv(here("data/iucn_threatened_spp_range_area_061826.csv"))
```

## EEZs

```{r}
eez <- st_read('/home/shares/usgs-cap-rangeshifts/spatial/World_EEZ_v12_20231025_gpkg/eez_v12.gpkg')
```

```{r}
eez <- st_read('/Users/abowd/World_EEZ_v12_20231025_gpkg/eez_v12.gpkg')
```

```{r}
# Get list of EEZ IDs that are not overlapping claims (i.e., POL_TYPE = 200NM)
eez_200nm_list <- eez %>% 
  filter(POL_TYPE == "200NM") %>% 
  pull(MRGID)

# Add Ukraine to list
eez_200nm_list <- c(eez_200nm_list, 5695)
```

```{r}
eez_simple <- eez %>% 
  dplyr::select(MRGID, GEONAME) %>% 
  st_drop_geometry() %>% 
  filter(MRGID %in% eez_200nm_list)

eez_simple_sf <- eez %>% 
  dplyr::select(MRGID, GEONAME) %>% 
  filter(MRGID %in% eez_200nm_list)
```

```{r}
# Create a blank raster matching AquaX resolution (EEZs should be large enough to just do 0.05 degree raster)
eez_raster_blank <- rast(xmin = -180,
                  xmax = 180,
                  ymin = -90, 
                  ymax = 90,
                  resolution = 0.05,
                  crs = "EPSG:4326")
```

```{r}
eez_raster_mrgid <- rasterize(eez_simple_sf, eez_raster_blank, field = "MRGID")
```

```{r}
# Create dataframe of EEZ raster
eez_raster_df <- as.data.frame(eez_raster_mrgid, xy = TRUE) %>% 
  # Round so that the X and Y match the AquaX data (which is rounded to 3 decimal places)
  mutate(x = round(x, 3),
         y = round(y, 3))
```

```{r}
ggplot() +
  geom_sf(data = eez_simple_sf) +
  coord_sf(expand = FALSE) +
  geom_tile(data = eez_raster_df, aes(x = x, y = y,
                              fill = MRGID,
                              color = MRGID)) 
```

## Bar graph by taxonomic group 

```{r}
iucn_lookup <- read_csv("https://raw.githubusercontent.com/nceas-range-shifts/chi_shifts/ab9cd09931a4ce5c12d0bcd2984595d6522ed158/_data/iucn_redlist_2026/iucn_worms_aphia_id_complete.csv")
```

```{r}
iucn_cat <- read_csv("https://raw.githubusercontent.com/nceas-range-shifts/chi_shifts/refs/heads/main/_data/iucn_redlist_2026/iucn_species_assessments.csv")
```

```{r}
# Add aphiaid to iucn_cat
iucn_cat_aphiaid <- left_join(iucn_cat, (iucn_lookup %>% dplyr::select(iucn_assessment_id, aphia_id)),
 by = c("assessment_id" = "iucn_assessment_id")) %>% 
  rename(aphiaid = aphia_id) 
```

```{r}
# Merge in iucn_cat to get group for each species
spp_eez_pxl_count_group <- left_join(spp_eez_pxl_count, iucn_cat_aphiaid)
```

 ```{r}
# read in meta data on the aquax species to get groups
load("/home/shares/data-aquax/META_02122025.Rdata")
```

```{r}
meta_clean <- META %>% 
  mutate(worms_name = tolower(ScientificName)) %>% 
  select(!ScientificName) %>% 
  # simplify for now for easier viewing
  select(AphiaID, SPID, worms_name, GROUP, phylum, class, family, HAB, NR_CR, range_pixels, SDM)
```

```{r}
spp_eez_group_meta <- left_join(spp_eez_pxl_count_group, meta_clean, by = c("aphiaid" = "AphiaID")) %>% 
    mutate(general_group = case_when(group %in% c("sharks_and_rays")~ "FISH: sharks & rays",
                                   group %in% c("tunas_and_billfishes") ~ "FISH: tunas & billfishes",
                                   TRUE ~ GROUP))
```

```{r}
# What's the count of each group 
spp_eez_group_count_meta <- spp_eez_group_meta %>% 
  group_by(general_group) %>% 
  summarise(n_spp = length(unique(aphiaid))) %>% 
  ungroup()
```

## Get list of species entries by EEZ

```{r}
# Organize dataframe so that's it's easier to select a scenario and compare to current
eez_spp_pxls_long <- spp_eez_group_meta %>% 
  pivot_longer(cols = starts_with("n_RCP"),
               names_to = "scenario",
               values_to = "pxl_count") %>% 
  mutate(scenario = str_remove(scenario, "n_")) %>% 
  # Replace NA with 0, otherwise will be assigned to "continued presence"
  mutate(pxl_count = replace_na(pxl_count, 0),
         n_current = replace_na(n_current, 0)) %>% 
  # Set 1 pixel threshold (at least one pixel needs to be in EEZ for species presence)
  mutate(spp_change = case_when(n_current < 1 &  pxl_count >= 1 ~ 'entry into new',
                            n_current >= 1  & pxl_count < 1 ~ 'exit from historical',
                            n_current < 1  & pxl_count < 1 ~ 'no presence',
                            TRUE ~ 'continued presence'))
```

```{r}
# Which species have the most EEZ region entries?
spp_eez_entry_count <- eez_spp_pxls_long %>% 
  filter(MRGID %in% eez_200nm_list) %>%
  filter(spp_change == "entry into new") %>% 
  group_by(aphiaid, scenario, general_group, group) %>% 
  summarise(n_eez_entry = n()) %>% 
  ungroup()

# Which species have the most EEZ region exits?
spp_eez_exit_count <- eez_spp_pxls_long %>% 
  filter(MRGID %in% eez_200nm_list) %>%
  filter(spp_change == "exit from historical") %>% 
  group_by(aphiaid, scenario, general_group, group) %>% 
  summarise(n_eez_exit = n()) %>% 
  ungroup()

# Get list of EEZ exits 90 and over
spp_exit_90 <- spp_eez_exit_count %>% 
  filter(n_eez_exit >= 90,
         scenario == "RCP45_2050")

spp_exit_90_list <- spp_exit_90$aphiaid
```

```{r}
# Bentfin devil ray - exits zero EEZs
bdr <- eez_spp_pxls_long %>% 
  filter(MRGID %in% eez_200nm_list) %>%
  filter(scenario == "RCP45_2050") %>%
  filter(spp_change == "entry into new") %>%
  filter(aphiaid == 217430)
  #filter(spp_change == "entry into new")
```


```{r}
# What about tracking entry and exit per species 
spp_eez_entry_exit_count <- full_join(spp_eez_entry_count, spp_eez_exit_count, by = c("aphiaid", "scenario")) %>% 
  mutate(n_eez_entry = replace_na(n_eez_entry, 0),
         n_eez_exit = replace_na(n_eez_exit, 0))
```

```{r}
# Area of 90 + species
area_df_90 <- area_df %>% 
  filter(aphiaid %in% spp_exit_90_list) %>% 
  filter(scenario == "RCP45_2050") %>%
  mutate(perc_of_current = scenario_area_km2 / current_area_km2 * 100)
```

## Bar graph

```{r}
# Get eez group counts
spp_eez_entry_count_iucn <- spp_eez_entry_count %>% 
  group_by(general_group, scenario, n_eez_entry) %>% 
  summarize(n_spp = n()) 

spp_eez_exit_count_iucn <- spp_eez_exit_count %>% 
  group_by(general_group, scenario, n_eez_exit) %>% 
  summarize(n_spp = n()) 
```

```{r}
spp_eez_entry_clean <- spp_eez_entry_count_iucn %>% 
  filter(scenario == "RCP45_2050") %>% 
  mutate(n_eez_entry_group = case_when(n_eez_entry >= 10 & n_eez_entry < 40 ~ "10+",
                                        n_eez_entry >= 40 & n_eez_entry < 80 ~ "40+",
                                         n_eez_entry >= 80 ~ "80+",
                                         TRUE ~ as.character(n_eez_entry)))

```

```{r}
spp_eez_entry_clean$n_eez_entry_group <- factor(spp_eez_entry_clean$n_eez_entry_group, 
levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10+", "40+", "80+"))
```

```{r}
spp_eez_exit_clean <- spp_eez_exit_count_iucn %>% 
  filter(scenario == "RCP45_2050") %>% 
  mutate(n_eez_exit_group = case_when(n_eez_exit >= 10 & n_eez_exit < 40 ~ "10+",
                                        n_eez_exit >= 40 & n_eez_exit < 80 ~ "40+",
                                         n_eez_exit >= 80 ~ "80+",
                                         TRUE ~ as.character(n_eez_exit)))
```

```{r}
spp_eez_exit_clean$n_eez_exit_group <- factor(spp_eez_exit_clean$n_eez_exit_group, 
levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10+", "40+", "80+"))
```

```{r}
spp_eez_exit_entry_clean <- rbind(spp_eez_exit_clean %>% 
                                  dplyr::select(general_group, scenario, n_eez_exit_group, n_spp) %>% 
                                  mutate(change = "Exits") %>% 
                                  rename(n_eez_group = n_eez_exit_group),
                                  spp_eez_entry_clean %>% 
                                  dplyr::select(general_group, scenario, n_eez_entry_group, n_spp) %>% 
                                  mutate(change = "Entries") %>% 
                                  rename(n_eez_group = n_eez_entry_group))
```

```{r}
spp_eez_exit_entry_clean$n_eez_group <- factor(spp_eez_exit_entry_clean$n_eez_group, 
levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10+", "40+", "80+"))
```

```{r}
entry_exit_barplot <- ggplot() +
  geom_bar(data = spp_eez_exit_entry_clean,
            aes(x = n_eez_group, y = n_spp, fill = general_group), stat = "identity") +
  scale_fill_viridis_d(option = "turbo", direction = 1) +
  scale_x_discrete(breaks = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10+", "40+", "80+")) +
  theme_minimal() +
  facet_wrap(~change) + 
  theme(legend.position = "bottom") +
  labs(title = "EEZ entries and exits by taxonomic group",
       x = "EEZ count",
       y = "Species count",
       fill = "")
  
```

```{r}
# Save bar plot
ggsave(here("figures/rcp45_2050/iucn_atrisk_taxon_entry_exit_rcp45_1pxl_091826.png"), entry_exit_barplot, width = 10, height = 8, dpi = 300)

```